# Generated by Django 5.0.6 on 2024-05-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('kWh_consumption', models.PositiveIntegerField()),
                ('escalator', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_id', models.CharField(max_length=255)),
                ('tariff_name', models.CharField(max_length=255)),
                ('pricing_matrix', models.JSONField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utility_app.project')),
            ],
        ),
    ]
